### PR TITLE
experiment with interface for fixing/fitting parameters

### PR DESCRIPTION
**Pull request by zkbt**
*(No need to pull this code into your `main` if you don't want to; I just opened a draft Pull Request because I think it's easiest way to be able to talk about code on a particular branch.)*

@catrionamurray, your `chromatic_model` and demo notebook are amazing! I got them to run smoothly on my computer, I was able to play around a bit with your fits, and I learned a ton by reading through how you had implemented things. Great work, and thank you!!!

Foreseeing many many many more "I wonder what it would look like if we fixed this and fitted that" experiments to come, I made an attempt at reorganizing the steps of your code to allow for a slightly friendlier interface for saying what's fixed and what's fitted, and what's shared across wavelengths and what's fitted for each wavelength. I was curious to see if we could separate that part out away from the actual model initialization, and I think maybe I got something useful working? 

The `test-flexible-parameters.ipynb` lays out a new set of `Parameter` classes that I think helps with this. I think it covers every type of quantity I saw in your code with a few general types of quantities. These `Parameter`-derived objects are basically little helpers that store all the information needed to initialize a prior when needed; I got the idea from your nice `Normal` and `Uniform` wrappers. With them, we can say "I want the prior to be like this" and then whenever we actually generate a PyMC3 model we can call their `.get_prior()` methods to drop in the appropriate value or distribution.

I put together two barebones fit examples in `test-fits-with-flexible-parameters.ipynb` showing how, I think, we might be able to use these new `Parameters` as a flexible interface for quickly trying lots of different kinds of fits. These don't use any of your lovely multistep fitting infrastructure or your pretty diagnostics; I was just trying to see if I could get something to work, but if you like this I'd love to talk about merging it all together! One big difference is that this new code uses a dictionary of `Parameter` objects to replace the many individual named variables that you needed to carry around. This dictionary can start from some default values, can be updated as needed to allow some parameters to vary, and keeps everything contained in one place so it's easy to loop through when needed. It relies a lot on that feature (that I still find magical) where `**kwargs` in a function definition will catch all keyword arguments supplied during the function call and store them in a `kwargs` dictionary, and vice versa to expand a dictionary into a bunch of keyword arguments when calling a function. This both allows parameters to have defaults that are only optionally updated and allows us to flexibly pass inputs for the PyMC3 distributions through to when we need to initialize. `.setup_parameters`, `.setup_orbit`, and `.setup_lightcurves` are the places where I think you see this dictionary getting the most use.

(As a weirdly specific thing, I think the `Fixed` parameter object replaces some of what you were doing with the `observed` keyword, but I'm not sure if it's doing things the same, so maybe we should talk about that at some point.)

Anyway, I'd be super curious to hear your thoughts on this reorganization. Does it work? Does it make sense? Is it helpful? Do you think this framework could actually capture all the different kinds of fits you've been experimenting with?

### CODE REVIEW

**Comment by catrionamurray** [comment]
Looks great! I especially like the Parameter reorganisation! If we wanted to move to this format we should maybe do it soon if we want this tool to be useable in July. I think it might take a bit of work to get it working with the fitting tools/to change my brain to thinking in this new format. There are a few bits I would want to talk through as well.

**Comment by catrionamurray** [comment]
Added PolynomialModel

**Comment by catrionamurray** [comment]
Example usage:
Screenshot 2022-06-10 at 13 45 38
Screenshot 2022-06-10 at 13 52 07

**Comment by zkbt** [comment]
Awesome! I haven't had time to look at it too closely, but did you figure out a way to merge two PyMC3 models together somehow for this?! Or is it still doing all the merging before actually initializing the model? Either way, this is super exciting and opens up a lot of cool flexibility!

**Comment by catrionamurray** [comment]
> 

You initialize the models separately and then combine them:
`cm = CombinedModel() `
`cm.initialize_empty_model()`
`cm.attach_models({'transit':t,'polynomial':b})`
With the parameters already defined in t and b. They way it works is by essentially creating a "copy" of the parameters of each and combining together into one model. I believe it has to be this way if you want to be able to optimise all the parameters at the same time. If you do t.setup_lightcurves() and b.setup_lightcurves() then you want to combine them I don't think you'll ever be able to do the optimization of all params at the same time because they're by definition different pymc3 models.

**Comment by catrionamurray** [comment]
White-light fit:
Screenshot 2022-06-10 at 15 45 01

**Comment by catrionamurray** [comment]
white light LC (polynomial model in cyan):
Screenshot 2022-06-10 at 16 00 20

**Pull request merged**
