### PR TITLE
Added Systematics modelling

### LINKED ISSUE #4: Add a linear systematics model.
In `chromatic`, you can make a cartoonish systematics-ridden dataset with 
```
(SimulatedRainbow()
 .inject_transit()
 .inject_systematics(amplitude=0.002)
 .inject_noise(signal_to_noise=500)
 .imshow())
```
It'd be good to have a model to match what goes into that systematics simulation. The final `model` used to generate the flux is `planet_model`*`systematics_model`, where `planet_model` should be 1 out of transit and `systematics_model` should wobble close to 1. 

The systematics injected (with the default inputs) are `S = a*x + b*y + c*time +d*background`, where some of those are `timelike` (x, y, time) and some are `fluxlike` (background). Those inputs are all stored in the appropriate dictionaries, so it should be possible to perfectly reconstruct the model and to fit for the coefficients [a, b, c, d].

image

image

I think that's a basic model that may really come in handy for some of the JWST datasets! It'd be similar to `PolynomialModel` but would need to specify which inputs should be uses as the independent variable(s) instead of time. Starting with something linear might be easiest to code up, with just 1 parameter per independent variable?

### PR DESCRIPTION
**Pull request by catrionamurray**
Added `degree` and `indep_var` to PolynomialModel that should allow us to keep parts of the polynomial fixed/avoid fitting a constant and let us fit to variables other than time (timelike + fluxlike), however I need to test this with Zach's most recent version of `chromatic`

### CODE REVIEW

**Comment by catrionamurray** [comment]
Fixed  bug in CombinedModel - now working for systematics model without transit:

```
time_p_1          0.045021
x_p_1             0.001340
y_p_1             0.001761
background_p_1   -0.002642
```

```
f = 1
  + c_x*(x - offset_x)/sigma_x
  + c_y*(y - offset_y)/sigma_y
  + c_time*(time - offset_time)/sigma_time
  + c_background*(background - offset_background)/sigma_background

            linear_x = 'c_x*(x - offset_x)/sigma_x'
                 c_x = 0.001302784077468495
            offset_x = 0
             sigma_x = 1
            linear_y = 'c_y*(y - offset_y)/sigma_y'
                 c_y = 0.0017690445319806084
            offset_y = 0
             sigma_y = 1
         linear_time = 'c_time*(time - offset_time)/sigma_time'
              c_time = 0.002695076044832677
         offset_time = <Quantity -0.00069444 d>
          sigma_time = <Quantity 0.06013932 d>
   linear_background = 'c_background*(background - offset_background)/sigma_background'
        c_background = -0.0026526629569606063
   offset_background = 0
    sigma_background = 1
```

Residuals ~ +/- 400ppm

systematics_model

**Comment by catrionamurray** [comment]
Added model operations from other pull request (adapted Zach's suggestions)

**Comment by catrionamurray** [comment]
It's a little hacky at parts - I had a struggle with the naming of parameters when you create a CombinedModel using the operations, I ended up in some recursive naming loops where I had p_0, p_1, x_p_0, x_p_1, x_x_p_0, x_x_p_1, etc...

**Comment by catrionamurray** [comment]
This now means, however, that you can do: 
`cm = b + b_x + b_y + b_bkg`
successfully! (see Systematic_Modelling.ipynb for demo!)

**Comment by catrionamurray** [comment]
Interestingly it doesn't fit well if I subtract one component instead of adding - shouldn't it just be the negative of the same coefficient, why would it change the outcome?

**Comment by zkbt** [comment]
I agree that's weird that it behaves differently for subtraction vs addition. Especially if you;re using a prior that's symmetric around zero, there shouldn't be any difference. Might be worth looping through ~10ish attempts with new systematics realizations? Could it potentially just be weird luck that it failed for one and not the other?

**Comment by catrionamurray** [comment]
I tried looping 10x, for every attempt I get the correct answer with all '+' and I get the wrong answer if I change one to '-'. I don't understand it, I have Normal distributions around 0 with sigma=0.01 so it should be symmetric!

**Comment by zkbt** [comment]
Fascinating! That is *extremely* weird. 🤔

The only thing I could think of is that `-` might somehow be acting differently than `+` in terms of PyMC3 generating the calculation graph for the model variables? Like `+` is doing that properly but `-` somehow isn't?

**Comment by catrionamurray** [comment]
I think I cracked it. The subtract_dicts(A,B) was not doing A-B, instead, it was doing B-A. This wouldn't matter for addition (or multiplication) as it's not order-dependent.

**Comment by catrionamurray** [comment]
I think (?!) that it's now also working for transit model * (sum of systematics) model (`cm = t * (b + b_x + b_y + b_bkg`)! Here's all the plots, the planet model + noise recovered once systematic model is subtracted, and the final residuals (for one posterior draw):

systematic_plus_transit_residuals

**Comment by catrionamurray** [comment]
See [Systematic_Modelling](https://github.com/catrionamurray/chromatic_fitting/blob/systematics_model/Systematic_Modelling.ipynb) notebook for this example!

**Pull request merged**
